{% set version = "0.4.0" %}

package:
  name: pywebp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/webp/webp-{{ version }}.tar.gz
  sha256: 9265565839ac938327705c5fbfa3d8ceeeb9b5a2c1c3367231caa0bad29464c7

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cffi
    - importlib-resources
    - libwebp
  run:
    - python
    - pillow
    - numpy
    - cffi

test:
  imports:
    - webp
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/anibali/pywebp
  summary: WebP Python bindings
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
