{% set version = "0.1.7" %}

package:
  name: pywebp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/webp/webp-{{ version }}.tar.gz
  sha256: 85c9795b82f67fe2a9316a391e16e5dee42a3b7a01eeb698ee5179544c73d6bf

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cffi
    - importlib-resources
    - libwebp
  run:
    - python
    - pillow
    - numpy
    - cffi

test:
  imports:
    - webp
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/anibali/pywebp
  summary: WebP Python bindings
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
