{% set version = "0.1.8" %}

package:
  name: pywebp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/webp/webp-{{ version }}.tar.gz
  sha256: 9e081ddb2749e47f85cdceb86214ab70b94eb160a825f0b36a182734434d7089

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cffi
    - importlib-resources
    - libwebp
  run:
    - python
    - pillow
    - numpy
    - cffi

test:
  imports:
    - webp
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/anibali/pywebp
  summary: WebP Python bindings
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
